export default [
    { index: 'T1', brand: 'Samsung', model: 'Galaxy S II', androidVersion: '4.1.2', additionalNotes: 'qa+s2@netguru.pl', status: 'Available'},
    { index: 'T3', brand: 'Samsung', model: 'Galaxy S3 Neo', androidVersion: '4.4.2', additionalNotes: 'qa+s3@netguru.pl', status: 'Available'},
    { index: 'T4', brand: 'LG', model: 'G3 S', androidVersion: '5.0.2', additionalNotes: 'qa+lgg3@netguru.pl', status: 'Available'},
    { index: 'T5', brand: 'Samsung', model: 'Galaxy Note 3', androidVersion: '5.0.0', additionalNotes: 'qa+note@netguru.pl', status: 'Available'},
    { index: 'T6', brand: 'HTC', model: 'One M8', androidVersion: '5.0.1', additionalNotes: 'qa+htc@netguru.pl', status: 'Available'},
    { index: 'T7', brand: 'Samsung', model: 'Galaxy S4 Mini', androidVersion: '4.4.2', additionalNotes: '', status: 'Unavailable'},
    { index: 'T10', brand: 'Motorola', model: 'Moto G', androidVersion: '6.0.1', additionalNotes: '', status: 'Available'},
    { index: 'T11', brand: 'LG', model: 'K10', androidVersion: '5.1.1', additionalNotes: 'Assigned to Maciek Kownacki only (Roboteam)', status: 'Available'},
    { index: 'T12', brand: 'Sony', model: 'Xperia M5', androidVersion: '5.1', additionalNotes: '', status: 'Unavailable'},
    { index: 'T13A', brand: 'Google', model: 'Nexus 6p', androidVersion: '6.0.1', additionalNotes: 'Assigned to Michał Jung only (Ghinwa)', status: 'Available'},
    { index: 'T13B', brand: 'Google', model: 'Nexus 6p', androidVersion: '7.0', additionalNotes: '', status: 'Available'},
    { index: 'T14', brand: 'Google', model: 'Nexus 5x', androidVersion: '6.0.1', additionalNotes: '', status: 'Available'},
    { index: 'T15', brand: 'LG', model: 'G5', androidVersion: '6.0.1', additionalNotes: '', status: 'Available'},
    { index: 'T16', brand: 'Samsung', model: 'Galaxy S7', androidVersion: '6.0.1', additionalNotes: '', status: 'Unavailable'},
    { index: 'T17', brand: 'Sony', model: 'Xperia Z5', androidVersion: '5.1.1', additionalNotes: '', status: 'Available'},
    { index: 'T18', brand: 'Samsung', model: 'Note 5', androidVersion: '5.1.1', additionalNotes: '', status: 'Available'},
]
